version: '3.8'

services:
  # --- NEW: PostgreSQL Database Service ---
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=pdm_user
      - POSTGRES_PASSWORD=pdm_password
      - POSTGRES_DB=pdm_database
    ports:
      - "5432:5432" # Expose Postgres port to the host for easy access
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  # --- Existing Monitoring Services ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Access Prometheus UI on http://localhost:9090
    depends_on:
      - postgres # Optional, but good practice to ensure DB starts first

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Access Grafana UI on http://localhost:3000
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=gafenatesting@gmail.com
      - GF_SMTP_PASSWORD=clzq axex gyzv cgwe
      - GF_SMTP_FROM_ADDRESS=gafenatesting@gmail.com
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
  # --- NEW: Volume for persisting database data ---
  postgres-data: